In [1]:
import numpy as np

##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [2]:
array = np.array([0,3,5.4,8], dtype="int")
print(array.ndim)
print(array.size)
array

1
4


array([0, 3, 5, 8])

##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [10]:
array2 = np.array([[1,2,6,7], [4,3,9,5]])
print(f"Boyut = {array2.ndim}")
print(f"Eleman Sayısı = {array2.size}")
print(f"Satır ve Sütun Sayısı = {array2.shape}")
print(" ")
array3 = np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])
print(f"Boyut = {array3.ndim}")
print(f"Eleman Sayısı = {array3.size}")
print(f"Satır ve Sütun Sayısı = {array3.shape}")

Boyut = 2
Eleman Sayısı = 8
Satır ve Sütun Sayısı = (2, 4)
 
Boyut = 3
Eleman Sayısı = 12
Satır ve Sütun Sayısı = (2, 2, 3)


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [11]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
array2[0,1]

2

In [13]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
array2[0,3]

7

In [16]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
array3[1,1,2]

9

In [22]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
array3[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [23]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [25]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
array2[0,1:3]

array([2, 6])

In [26]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
array2[1,1:4]

array([3, 9, 5])

In [24]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [29]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
array3[0,1:]

array([[21,  8, 11]])

In [35]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
array3[1,0,1:3]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [40]:
array0 = np.zeros((5,3),dtype="int")
array1 = np.ones((5,3),dtype="int")

In [43]:
satir = np.concatenate([array0, array1], axis=0)
sutun = np.concatenate([array0, array1], axis=1)
print("Satır Bazında Birleştirme:\n", satir)
print("Sütun Bazında Birleştirme:\n", sutun)

Satır Bazında Birleştirme:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Sütun Bazında Birleştirme:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
